steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull asia-east1-docker.pkg.dev/cellular-cider-495602-r9/cloud-run-source-deploy/smart-audio:latest || true
        docker build --cache-from asia-east1-docker.pkg.dev/cellular-cider-495602-r9/cloud-run-source-deploy/smart-audio:latest -f Dockerfile.audio -t asia-east1-docker.pkg.dev/cellular-cider-495602-r9/cloud-run-source-deploy/smart-audio:latest .
images:
  - 'asia-east1-docker.pkg.dev/cellular-cider-495602-r9/cloud-run-source-deploy/smart-audio:latest'
options:
  machineType: 'E2_HIGHCPU_8'
timeout: '3600s'
